### ISSUE TITLE
Chess:+Move+E6+to+E7

### ISSUE THREAD

**Issue by AstroSquared** [marcizhu/marcizhu#2817]
Please+do+not+change+the+title.+Just+click+"Submit+new+issue".+You+don't+need+to+do+anything+else+:D

**Comment by marcizhu** [comment]
Hmmm... Is it? It should work regardless of the platform. @SquaredStudios-MC could you please give me more info on what browser did you use? I'd like to fix this issue.

**Comment by SquaredStudios-MC** [comment]
> Hmmm... Is it? It should work regardless of the platform. @SquaredStudios-MC could you please give me more info on what browser did you use? I'd like to fix this issue.

I am using the mobile app. I believe it's an issue with the app and not anything you did.

**Comment by SquaredStudios-MC** [comment]
https://user-images.githubusercontent.com/67833955/227059207-9ac49ed3-342c-4125-870c-49eadc96556a.MOV

**Comment by SquaredStudios-MC** [comment]
I believe my phone is taking the + in the issue URL literally.
