### ISSUE TITLE
Duplicate moves @marcizhu

### ISSUE THREAD

**Issue by shpatrickguo** [marcizhu/marcizhu#535]
<img width="748" alt="Screen Shot 2021-07-07 at 16 18 08" src="https://user-images.githubusercontent.com/70539478/124840058-f5383500-df3e-11eb-93a5-226f9e450d61.png">

**Comment by marcizhu** [comment]
This is a known issue (see [marcizhu/readme-chess#2](https://github.com/marcizhu/readme-chess/issues/2). It will be fixed soon. Thanks for reporting though! <3

**Comment by marcizhu** [comment]
This is now fixed as of the latest commit (54e3a6c). This is fixed in [marcizhu/readme-chess](https://github.com/marcizhu/readme-chess) as well.
